name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Greeting Message
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '👋 Hello! Thanks for submitting your first issue. We appreciate your contribution to the project!'
        pr-message: '👋 Welcome! Thank you for your first pull request. We are excited to see your contribution!'
